
INSERT INTO TALRCAGDEMTL
(
 FEE_MODL_CD
, TRGT_RCAG_CNT
)
VALUES
(
 #{FEE_MODL_CD}
, #{TRGT_RCAG_CNT}
)

UPDATE TALRCAGDEMTL
SET
    FEE_MODL_CD   = #{FEE_MODL_CD}
    , TRGT_RCAG_CNT = #{TRGT_RCAG_CNT}
WHERE FEE_MODL_CD   = #{FEE_MODL_CD}